#!/usr/bin/env bash
set -euo pipefail

# Post push hook for Docker Hub
# Tags the builds with apt tags for each of the versions.
# Goes through each version in order and tags them with each component of
# their version. Thus the order matters, and you should generally not add
# multiple versions of the same major and minor to one build.

# shellcheck source=../tags.sh
source "${BASH_SOURCE%/*}/../tags.sh"

function tags() {
  VERSION=$1
  VERSION_PARTS="${VERSION//[^.]/}"
  VERSION_PARTS=$((${#VERSION_PARTS} + 1))
  PARAMETERS=()
  for ((i = 1; i <= VERSION_PARTS; i++)); do
    PARAMETERS+=("$(echo "$VERSION" | cut -d. -f "1-$i")")
  done
  if [ "$VERSION" == "$LATEST_STABLE" ]; then
    PARAMETERS+=("latest")
  elif [ "$VERSION" == "$LATEST_PREVIEW" ]; then
    PARAMETERS+=("latest-preview")
  fi
  echo "${PARAMETERS[@]}"
}

for version in "${VERSIONS[@]}"; do
  unset IMAGES
  read -ra IMAGES < <(tags "$version")
  for image in "${IMAGES[@]}"; do
    $BUILDER push "$NAME:$image"
  done
  true
done
